version: '3'

services:
  mysql8:
    image: mysql:8.0.29
    container_name: mysql8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: febsA123
    ports:
      - "3306:3306"
    volumes:
      - /febs/mysql/data:/var/lib/mysql #挂载 MySQL数据
  redis:
    image: redis:5
    restart: always
    container_name: redis
    volumes:
      - /febs/redis/data:/data #挂载 Redis数据
    ports:
      - "6379:6379"
  nacos:
    image: nacos/nacos-server:v2.0.4
    container_name: nacos-standalone-mysql
    environment:
      MODE: standalone
      PREFER_HOST_MODE: hostname
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: mysql8
      MYSQL_SERVICE_DB_NAME: nacos
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: febsA123
      MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    volumes:
      - /febs/standalone-logs/:/home/nacos/logs
      - ./nacos-custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      - mysql8
    restart: always