shenyu:
  database:
    dialect: mysql
    init_script: "sql-script/mysql/schema.sql"
    init_enable: true

spring:
  datasource:
    url: jdbc:mysql://mysql8:3306/shenyu?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: febsA123
    driver-class-name: com.mysql.jdbc.Driver